        # SPDX-License-Identifier: MIT
        # Copyright (c) 2020-2022 Advanced Micro Devices, Inc. All rights reserved.
        # Defaults
log_prefix = "fort2x.codegen"
        # Prefix for log output that this component writes.

cpp_file_preamble = "// This file was generated by GPUFORT\n"
        # Preamble to write at the top of the generated HIP C++ files.
        # Use it to place a copyright message at the top
        # of a file, for example.

fortran_module_preamble = "! This file was generated by GPUFORT\n"
        # Preamble to write at the top of the generated Fortran module file.
        # Use it to place a copyright message at the top
        # of a file, for example.

fortran_module_suffix = "_fort2x"
        # Suffix for generated hip modules.

fortran_module_file_ext = "-fort2x.f08"
        # Suffix appended to the generated Fortran module.

cpp_file_ext = "-fort2x.cpp"
        # Suffix appended to the generated C++ files.

fortran_default_modules = [
    "iso_c_binding",
    "hipfort",
    "gpufort_array",
]
cpp_default_includes = [
    "gpufort.h",
    "gpufort_reduction.h",
    "gpufort_array.h",
]

def default_namespace_per_scope_parameter_filter(scope_tag,f_type,f_kind,name,rank):
    return False
def default_namespace_per_scope_prepend_callback(scope_tag):
    """:return C++ code lines to prepend to the
    body of the namespace mapped to the scope tag."""
    return []
def default_namespace_per_scope_append_callback(scope_tag):
    """:return C++ code lines to prepend to the
    body of the namespace mapped to the scope tag."""
    return []

namespace_per_scope_parameter_filter = default_namespace_per_scope_parameter_filter
        # Selector for parameter types that should be mapped to the C++ namespace derived
        # from the scope with the given tag. 
namespace_per_scope_prepend_callback = default_namespace_per_scope_prepend_callback
        # C++ code lines to prepend to the
        # body of the namespace derived from the scope tag."""
namespace_per_scope_append_callback = default_namespace_per_scope_append_callback
        # C++ code lines to append to the
        # body of the namespace derived from the scope tag."""
