// SPDX-License-Identifier: MIT
// Copyright (c) 2020-2022 Advanced Micro Devices, Inc. All rights reserved.
// This file was generated by gpufort
#ifndef __KERNELS_HIP_CPP__
#define __KERNELS_HIP_CPP__
#include "hip/hip_runtime.h"
#include "hip/hip_complex.h"
#include "gpufort.h"
#include "gpufort_array.h"


// BEGIN main_26_e28c45
/*
   HIP C++ implementation of the function/loop body of:

     !$cuf kernel do(1) <<<grid, tBlock>>>
     do i=1,size(y_d,1)
       y_d(i) = y_d(i) + a*x_d(i)
     end do

*/

__global__ void  vecadd_kernel(
    gpufort::array1<float> y_d,
    const float a,
    const gpufort::array1<float> x_d
) {
  int i = 1 + (1)*(threadIdx.x + blockIdx.x * blockDim.x);
  if (loop_cond(i,y_d.size(1),1)) {
    y_d(i)= y_d(i) + a*x_d(i);
  }
}

extern "C" void launch_vecadd_kernel_(
    const dim3& grid,
    const dim3& block,
    const int& sharedmem, 
    hipStream_t& stream,
    gpufort::array1<float>& y_d,
    const float& a,
    const gpufort::array1<float>& x_d
) {
  // launch kernel
  hipLaunchKernelGGL((vecadd_kernel), grid, block, sharedmem, stream, y_d, a, x_d);
  //y_d.print_host_data(std::cout,"launch_vecadd_kernel:y_d:host",gpufort::PrintMode::PrintCValues,12);
  //y_d.print_device_data(std::cout,"launch_vecadd_kernel:y_d:device",gpufort::PrintMode::PrintValuesAndNorms,12);
}
// END vecadd_kernel
#endif // __KERNELS_HIP_CPP__ 