// This file was generated by GPUFORT

#ifndef DATATYPES_FORT2X_CPP
#define DATATYPES_FORT2X_CPP
#include "gpufort.h"
#include "gpufort_reduction.h"
#include "gpufort_array.h"
#endif // DATATYPES_FORT2X_CPP