// This file was generated by GPUFORT

#ifndef VECTOR_ADD_F90_GPUFORT_CPP
#define VECTOR_ADD_F90_GPUFORT_CPP
#include "cudafor-fort2x.cpp"

// BEGIN main_28 e28c45

/**
   HIP C++ implementation of the function/loop body of:

     !$cuf kernel do(1) <<<grid, tBlock>>>
     do i=1,size(y_d,1)
       y_d(i) = y_d(i) + a*xi
     end do

*/

__global__ void  main_28(
    gpufort::array1<float> y_d,
    int i,
    float a,
    gpufort::array1<float> x_d
){
  int i = 1 + (1)*(threadIdx.x + blockIdx.x * blockDim.x);
  if (loop_cond(i,y_d_n1,1)) {
    y_d(i)=(y_d(i)+a*x_d(i));
  }
}

// END main_28 e28c45

// BEGIN main_28 e28c45

extern "C" hipError_t launch_main_28_hip_(
    dim3& grid,
    dim3& block,
    const int& sharedmem,
    hipStream_t& stream,
    gpufort::array1<float>& y_d,
    int& i,
    float& a,
    gpufort::array1<float>& x_d) {
  hipError_t ierr = hipSuccess;
  hipLaunchKernelGGL((main_28), grid, block, sharedmem, stream, y_d,i,a,x_d);
  #if defined(SYNCHRONIZE_ALL) || defined(SYNCHRONIZE_main_28)
  HIP_CHECK(hipStreamSynchronize(stream));
  #elif defined(SYNCHRONIZE_DEVICE_ALL) || defined(SYNCHRONIZE_DEVICE_main_28)
  HIP_CHECK(hipDeviceSynchronize());
  #endif
  ierr = hipGetLastError();	
  if ( ierr != hipSuccess ) return ierr;
  return ierr;
}

extern "C" hipError_t launch_main_28_hip_ps_(
    dim3& problem_size,
    dim3& block,
    const int& sharedmem,
    hipStream_t& stream,
    gpufort::array1<float>& y_d,
    int& i,
    float& a,
    gpufort::array1<float>& x_d) {
  hipError_t ierr = hipSuccess;
  dim3 grid(divideAndRoundUp(problem_size.x,block.x),
            divideAndRoundUp(problem_size.y,block.y),
            divideAndRoundUp(problem_size.z,block.z));   
  hipLaunchKernelGGL((main_28), grid, block, sharedmem, stream, y_d,i,a,x_d);
  #if defined(SYNCHRONIZE_ALL) || defined(SYNCHRONIZE_main_28)
  HIP_CHECK(hipStreamSynchronize(stream));
  #elif defined(SYNCHRONIZE_DEVICE_ALL) || defined(SYNCHRONIZE_DEVICE_main_28)
  HIP_CHECK(hipDeviceSynchronize());
  #endif
  ierr = hipGetLastError();	
  if ( ierr != hipSuccess ) return ierr;
  return ierr;
}

// END main_28 e28c45
#endif // VECTOR_ADD_F90_GPUFORT_CPP