TEST     ?= parallel-loop-1
DEPS     ?= 
LDFLAGS ?= -v -fopenacc # -foffload=amdgcn-amdhsa="-march=gfx900" -offload=-lgfortran
CFLAGS ?= -v -fopenacc  # -foffload=amdgcn-amdhsa="-march=gfx900" -offload=-lgfortran

include ../Makefile.in
