# SPDX-License-Identifier: MIT
# Copyright (c) 2020-2022 Advanced Micro Devices, Inc. All rights reserved.
import os

__GPUFORT_INC_DIR = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                                 "../include")
include_dirs = [__GPUFORT_INC_DIR]
# Include dir for gpufort_mod file and header files.

post_cli_actions = []
# List of actions to run after parsing the command line arguments
# Note that config is read before parsing other command line arguments.
# Register functions with parameters (args,unknown_args) (see: argparse.parse_known_args

# logging
log_level = "warning"
# Log level; only print warnings by default.
log_format = "[%(levelname)s][infile:%(filename)s] gpufort:%(message)s"
# Log format
log_prefix = "gpufort"
# Prefix for all log output
only_create_gpufort_module_files = False
# Only create and write GPUFORT module files and no other output.
skip_create_gpufort_module_files = False
# Skip creating and writing GPUFORT module files.

only_modify_translation_source = False
# Do only modify the translation source.
only_emit_kernels_and_launchers = False
# Do only emit/extract HIP C++ kernels and respective launchers. (Only makes sense if destination language is HIP.)
only_emit_kernels = False
# Do only emit/extract HIP C++ kernels but no launchers. (Only makes sense if destination language is HIP.)

fortran_file_preamble = "! This file was generated by GPUFORT\n"
# Preamble to write at the top of the modified translation source.
# Use it to place a copyright message at the top
# of a file, for example.

fortran_file_ext = "-gpufort.f08"
# Suffix for the modified Fortran file.
fortran_prettifier = None
# Prettify GPUFORT's Fortran output with the command specified here.
# (Use {file} as placeholder for the input file.)
# Set this variable to None to disable Fortran output prettification.
cpp_file_ext = "-gpufort.cpp"
# Suffix appended to the generated GPUFORT C++ files.
cpp_prettifier = None
# Prettify GPUFORT's C++ output with the command specified here.
# (Use {file} as placeholder for the input file.)
# Set this variable to None to disable C++ output prettification.
profiling_enable = False
# Enable profiling of GPUFORT
profiling_output_num_functions = 50
# Number of functions to output when profiling GPUFORT

dump_linemaps = False
# Write the lines-to-statements mappings to disk before & after
# applying code transformations; suffix="-linemaps-(pre|post).json"
