! SPDX-License-Identifier: MIT
! Copyright (c) 2020-2022 Advanced Micro Devices, Inc. All rights reserved.
module types
  use iso_c_binding
  use gpufort_array

  ! original non-interoperable types
  type :: node_t
    real :: val
  end type

  type :: mesh_t
    real :: a
    type(node_t),allocatable  :: x(:)
    real,pointer,dimension(:) :: y
  end type

  ! interoperable types; (will be) autogenerated by GPUFORT
  type,bind(c) :: node_t_interop
    real(c_float) :: val
  end type

  type,bind(c) :: mesh_t_interop
    real(c_float)        :: a
    type(gpufort_array1) :: x
    type(gpufort_array1) :: y
  end type
end module

program main
  use types
  use hipfort_check
  implicit none
  integer, parameter :: N = 40000
  !
  type(mesh_t)         :: mesh_orig
  type(mesh_t_interop) :: mesh_interop
  !
  call init_orig_type() 

  call init_interop_type()
  
  call launch_vecadd_kernel_auto(0,c_null_ptr,mesh_interop)

  call destroy_interop_type()

  write(*,*) 'Max error: ', maxval(abs(mesh_orig%y-4.0))
contains
  subroutine init_orig_type()
    implicit none
    integer i
    allocate(mesh_orig%x(N))
    allocate(mesh_orig%y(N))
    mesh_orig%x(:)%val = 1.0; 
    mesh_orig%y(:) = 2.0; mesh_orig%a = 2.0
  end subroutine

  ! (will be) autogenerated by gpufort
  subroutine init_interop_type()
    use gpufort_array
    use iso_c_binding
    implicit none
    integer i
    type(node_t_interop)         :: node_t_interop_dummy
    type(node_t_interop),pointer :: mesh_t_interop_x(:)
    ! Allocate interoperable struct array
    ! Generate type specific init routine?
    ! REQ: Need to know shape and bounds, not mesh_orig
    ! NOTE: size can be supplied from the CPP side, too.
    ! NOTE: alloc_mode will remain as is.
    call hipCheck(gpufort_array_init(mesh_interop%x,&
      int(c_sizeof(node_t_interop_dummy),c_int),&
      shape(mesh_orig%x),&
      lbounds=lbound(mesh_orig%x),&
      alloc_mode=gpufort_array_alloc_pinned_host_alloc_device)) 

    ! Copy to device; from non-interop type to interop type
    ! REQ: Need to know mesh_orig for value assignment
    call c_f_pointer(mesh_interop%x%data%data_host,&
      mesh_t_interop_x,shape=shape(mesh_orig%x))
    mesh_t_interop_x(:)%val = mesh_orig%x(:)%val ! depends on members & rank
    call hipCheck(gpufort_array_copy_to_device(mesh_interop%x))

    ! Init basic datatype array 
    call hipCheck(gpufort_array_init(mesh_interop%y,mesh_orig%y,&
      alloc_mode=gpufort_array_wrap_host_alloc_device,&
      sync_mode=gpufort_array_sync_copy))
    mesh_interop%a = mesh_orig%a
  end subroutine
 
  ! (will be) autogenerated by GPUFORT
  subroutine destroy_interop_type()
    use gpufort_array
    use iso_c_binding
    implicit none
    call hipCheck(gpufort_array_destroy(mesh_interop%x))
    call hipCheck(gpufort_array_destroy(mesh_interop%y))
  end subroutine
end program main