module types
  use iso_c_binding
  use gpufort_array
  ! original non-interoperable type
  type :: mesh_t
    real :: a
    real,allocatable :: x(:), y(:)
  end type

  ! interoperable type; (will be) autogenerated by GPUFORT
  type,bind(c) :: mesh_t_interop
    real(c_float)        :: a
    type(gpufort_array1) :: x, y
  end type
end module

program main
  use types
  use hipfort_check
  implicit none
  integer, parameter :: N = 40000
  !
  type(mesh_t)         :: mesh_orig
  type(mesh_t_interop) :: mesh
  type(c_ptr)          :: stream = c_null_ptr
  !
  call create_original_type(mesh_orig,stream) 
  call copy_to_intermediate_type(mesh_orig,mesh,stream)
  
  call launch_vecadd_kernel_auto(0,stream,mesh)

  call destroy(mesh,stream)

  write(*,*) 'Max error: ', maxval(abs(mesh_orig%y-4.0))
contains
  subroutine create_original_type(mesh_orig,stream)
    use types
    use hipfort
    use hipfort_check
    implicit none
    type(mesh_t),intent(inout) :: mesh_orig
    type(c_ptr),intent(in)     :: stream
    !
    allocate(mesh_orig%x(N))
    allocate(mesh_orig%y(N))
    mesh_orig%x = 1.0; mesh_orig%y = 2.0; mesh_orig%a = 2.0
  end subroutine

  ! (will be) autogenerated by gpufort
  subroutine copy_to_intermediate_type(mesh_orig,mesh,stream)
    use types
    use hipfort
    use hipfort_check
    implicit none
    type(mesh_t),intent(in)            :: mesh_orig
    type(mesh_t_interop),intent(inout) :: mesh
    type(c_ptr),intent(in)             :: stream
    !
    call hipCheck(gpufort_array_init(mesh%x,mesh_orig%x,&
      alloc_mode=gpufort_array_wrap_host_alloc_device,&
      sync_mode=gpufort_array_sync_copyin,&
      stream=stream))
    call hipCheck(gpufort_array_init(mesh%y,mesh_orig%y,&
      alloc_mode=gpufort_array_wrap_host_alloc_device,&
      sync_mode=gpufort_array_sync_copy,&
      stream=stream))
    mesh%a = mesh_orig%a
  end subroutine
 
  ! (will be) autogenerated by GPUFORT
  subroutine destroy(mesh,stream)
    use types
    use hipfort
    use hipfort_check
    type(mesh_t_interop),intent(inout) :: mesh
    type(c_ptr),intent(in)             :: stream
    !
    call hipCheck(gpufort_array_destroy(mesh%x,stream))
    call hipCheck(gpufort_array_destroy(mesh%y,stream))
  end subroutine
end program main