// This file was generated by GPUFORT

#ifndef DEVICELIB_FORT2X_CPP
#define DEVICELIB_FORT2X_CPP
#include "gpufort.h"
#include "gpufort_reduction.h"
#include "gpufort_array.h"

// BEGIN devicefun 

/**
   HIP C++ implementation of the function/loop body of:

      attributes(device) subroutine deviceFun(a,x,y,N)
        implicit none
        integer :: N
        real :: x, y, a
        y = y + a*x
      end subroutine

*/

__global__ void  devicefun(
    UNKNOWN UNKNOWN,
    UNKNOWN UNKNOWN,
    UNKNOWN UNKNOWN,
    UNKNOWN UNKNOWN
){
  y=(y+a*x);

}

// END devicefun 
#endif // DEVICELIB_FORT2X_CPP