# SPDX-License-Identifier: MIT                                                
# Copyright (c) 2021 GPUFORT Advanced Micro Devices, Inc. All rights reserved.
import pyparsing
import re

def tokenize(statement,padded_size=0):
    """Splits string at whitespaces and substrings such as
    'end', '$', '!', '(', ')', '=>', '=', ',' and "::".
    Preserves the substrings in the resulting token stream but not the whitespaces.
    :param str padded_size: Always ensure that the list has at least this size by adding padded_size-N empty
               strings at the end of the returned token stream. Has no effect if N >= padded_size. 
               Disable padding by specifying value <= 0.
    """
    tokens1 = re.split(r"\s+|\t+",statement)
    tokens  = []
    for tk in tokens1:
        tokens += [part for part in re.split('(end|else|!\$?|(c|\*)\$|[(),]|::?|=>?|<<<|>>>|(<|>)=?|(/|=)=|(\.\w+\.))',tk,0,re.IGNORECASE)]
    result = [tk for tk in tokens if tk != None and len(tk)]
    if padded_size > 0 and len(result) < padded_size:
        return result + [""]*(padded_size-len(result))
    else:
        return result

def replace_all(f_snippet,ppexpression,repl=lambda parse_result: ("",False),strip_search_string=True):
    """Replaces all matches for the given pyparsing expression with
    the string generated by the 'repl' function argument, 
    which takes the pyparsing parse result into account.
    """
    matched     = True
    transformed = False
    used_list    = []
    while matched:
        matched = False
        for tokens,begin,end in ppexpression.scanString(f_snippet):
             parse_result = tokens[0]
             subst, changed = repl(parse_result)
             transformed |= changed
             if not begin in used_list:
                 if changed:
                     search_string = f_snippet[begin:end]
                     if strip_search_string:
                         search_string = search_string.strip().strip("\n").strip()
                     f_snippet = f_snippet.replace(search_string,subst)
                 else:
                     used_list.append(begin) # do not check this match again
                 matched = True
                 break
    return f_snippet, transformed
def replace_first(f_snippet,ppexpression,repl=lambda parse_result: ("",False),strip_search_string=True):
    """Replaces the first match for the given pyparsing expression with
    the string generated by the 'repl' function argument, 
    which takes the pyparsing parse result into account.
    """
    transformed = False
    for tokens,begin,end in ppexpression.scanString(f_snippet):
        parse_result = tokens[0]
        subst, transformed = repl(parse_result)
        if transformed:
            search_string = f_snippet[begin:end]
            if strip_search_string:
                search_string = search_string.strip().strip("\n").strip()
            f_snippet = f_snippet.replace(search_string,subst)
        break
    return f_snippet, transformed

def erase_all(f_snippet,ppexpression,strip_search_string=True):
    """Removes all matches for the given pyparsing expression
    """
    matched     = True
    transformed = False
    used_list    = []
    while matched:
        matched = False
        for tokens,begin,end in ppexpression.scanString(f_snippet):
            if not begin in used_list:
                search_string = f_snippet[begin:end]
                if strip_search_string:
                    search_string = search_string.strip().strip("\n").strip()
                f_snippet = f_snippet.replace(search_string,"")
                matched = True
                break
            transformed |= matched
    return f_snippet, transformed
def erase_first(f_snippet,ppexpression,strip_search_string=True):
    """Replaces the first match for the given pyparsing expression with
    the string generated by the 'repl' function argument, 
    which takes the pyparsing parse result into account.
    """
    transformed = False
    for tokens,begin,end in ppexpression.scanString(f_snippet):
        search_string = f_snippet[begin:end]
        if strip_search_string:
            search_string = search_string.strip().strip("\n").strip()
        f_snippet = f_snippet.replace(search_string,"")
        transformed = True
        break
    return f_snippet, transformed
